name: Build-Publish

on:
  push:
    branches: [master]
  release:
    types: [released]

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Git tag or branch slug
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            SLUG="${GITHUB_REF#refs/tags/}"
          fi

          echo "TAG=$SLUG" >> $GITHUB_ENV

      - name: Docker Build
        run: make build TAG=${TAG}

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Push
        run: make push TAG=${TAG}
